ARG BASE_IMAGE=quay.io/modh/odh-generic-data-science-notebook:v2-2023a-20230322
# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

# COPY Pipfile.lock /opt/app-root/bin/

USER 0

# hadolint ignore=DL3003
RUN dnf upgrade -y --refresh && \
    pip install ultralytics --no-cache-dir

# Download and extract FFmpeg static build
RUN wget -O ffmpeg-release.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-i686-static.tar.xz && \
    tar -xf ffmpeg-release.tar.xz && \
    cp ffmpeg-*/ffmpeg ffmpeg-*/ffprobe /usr/local/bin/ && \
    rm -rf ffmpeg-release.tar.xz ffmpeg-*
    
USER 1001