ARG BASE_IMAGE=quay.io/modh/odh-generic-data-science-notebook:v2-2023a-20230322
# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

USER 0

# Enable EPEL and RPM Fusion repositories and install ffmpeg
RUN dnf install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf install -y \
    https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm && \
    dnf install -y ffmpeg && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Install ultralytics
RUN pip install ultralytics --no-cache-dir

USER 1001

