ARG BASE_IMAGE=quay.io/modh/odh-generic-data-science-notebook:v2-2023a-20230322
# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

# COPY Pipfile.lock /opt/app-root/bin/

USER 0

# hadolint ignore=DL3003
# RUN dnf upgrade -y --refresh && \
#     pip install dlib==19.* --no-cache-dir

# Setup epel repository
RUN dnf install -y codeready-builder-for-rhel-9-x86_64-rpms \
https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm \
https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm 

RUN dnf config-manager --set-enabled codeready-builder-for-rhel-9-x86_64-rpms

# Install ffmpeg
RUN dnf install ffmpeg

# RUN pip install ffmpeg-python



USER 1001
