kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"cvstreamer:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cvstreamer\")].image"}]'
  name: cvstreamer
  namespace: cvdemo
  labels:
    app: cvstreamer
    app.kubernetes.io/component: cvstreamer
    app.kubernetes.io/instance: cvstreamer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: cvstreamer
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: cvstreamer
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: cvstreamer
          image: 'image-registry.openshift-image-registry.svc:5000/cvdemo/cvstreamer:latest'
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
